language: node_js

cache: npm

git:
  depth: 1

jobs:
  include:
    - &test
      stage: Test
      node_js: "10"
      before_install: npm install -g npm@latest
      install: npm ci
      script:
        - npm audit
        - npm test
    - &test-compatibility
      stage: Compatibility
      node_js: "node"
      os: linux
      install:
        - npm install
        - npm update
      script:
        - npm test
    - <<: *test-compatibility
      node_js: "10"
    - <<: *test-compatibility
      node_js: "11"
    - <<: *test-compatibility
      node_js: "12"
    - <<: *test-compatibility
      node_js: "13"
    - <<: *test
      stage: Analyze
      name: Sonarcloud
      dist: trusty
      addons:
        sonarcloud:
          organization: "getyoti"
      if: type == pull_request OR branch = master
      script:
        - npm test
        - sonar-scanner
